export const assets = {
  achievement_icon: require('assets/images/achievement_icon.png'),
  child_icon: require('assets/images/child_icon.png'),
  home_icon: require('assets/images/home_icon.png'),
  parent_icon: require('assets/images/parent_icon.png'),
  rank_icon: require('assets/images/rank_icon.png'),
  achievement_icon_new: require('assets/images/achievement_icon_new.png'),
  child_icon_new: require('assets/images/child_icon_new.png'),
  home_icon_new: require('assets/images/home_icon_new.png'),
  lock_icon: require('assets/images/lock_icon.png'),
  parent_icon_new: require('assets/images/parent_icon_new.png'),
  purchase_icon: require('assets/images/purchase_icon.png'),
  rank_icon_new: require('assets/images/rank_icon_new.png'),
  setting_icon: require('assets/images/setting_icon.png'),
  sound_icon: require('assets/images/sound_icon.png'),
  hexagon_frame: require('assets/images/hexagon_frame.png'),
  onboarding: require('assets/images/ONBOARDINGSCREEN.png'),
  book: require('assets/images/book.png'),
  star: require('assets/images/star.png'),
  untitled_artwork: require('assets/images/untitled_artwork.png'),
};
