# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build AAB"
  lane :buildAab do
    gradle(task: "clean bundleRelease")
  end

  desc "Build and upload APK to Firebase App Distribution"
  lane :upload_to_firebase do
    # gradle(task: "assembleRelease")

    firebase_app_distribution(
      app: "1:827845646125:android:61618b15b8dab04bf625a4",
      firebase_cli_token: "1//0eoz3S6LpCLt9CgYIARAAGA4SNwF-L9IrDR3gSYYfWxmfhoeqG5TBuoeJBIYzoGCZOajUoHMwKGkDGUC5Cv6UuLaICEePCQmLIbE",
      apk_path: "./app/build/outputs/apk/release/app-release.apk",
      release_notes: "New release",
      testers: "longnn17.developer@gmail.com",
      groups: "qa-team", # Comma-separated list of groups
      debug: true
    )
  end
end
